### ISSUE TITLE
Add `autoreconf -i` step to doc/INSTALL

### ISSUE THREAD

**Issue by Sodbo** [GenABEL-Project/ProbABEL#43]
If you want to compile ProbABEL by yourself, first you need to run `./configure` script.
In doc/INSTALL it is written as `./configure` script is already exist in ProbABEL folder.
But there is no `./configure` file. You need to create it by `autoreconf -i`

**Comment by lckarssen** [comment]
Hi Sodbo,

If you clone the git repository you indeed need to run `autoreconf -i`, this is actually mentioned [in line 53 of doc/INSTALL](https://github.com/GenABEL-Project/ProbABEL/blob/master/doc/INSTALL#L53) (although we only mention SVN there, not git).

**Comment by lckarssen** [comment]
I replaced the reference to SVN with Github in commit 681c76f.
